config/routes.rb
Brazilenglish::Application.routes.draw do
  root "pages#home"
  get "about" => "pages#about"
  get "lessons" => "pages#lessons"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

	def about
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
	<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
 <%=link_to "Sing Brazil", root_path, class: "navbar-brand" %>
     </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Lessons", lessons_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 
  <title>Brazilenglish</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>

</style> 
</head>
<body>
	<%= render 'layouts/header' %>
	
	<div class="container">
		<%= yield %>
	</div>
</body>

<footer>
  <div class="container">
  	
    <ul class="nav">
      <li><a href="https://www.iubenda.com/privacy-policy/735465" class="iubenda-black no-brand iubenda-embed" title="Privacy Policy">Privacy Policy</a><script type="text/javascript">(function (w,d) {var loader = function () {var s = d.createElement("script"), tag = d.getElementsByTagName("script")[0]; s.src = "https://cdn.iubenda.com/iubenda.js"; tag.parentNode.insertBefore(s,tag);}; if(w.addEventListener){w.addEventListener("load", loader, false);}else if(w.attachEvent){w.attachEvent("onload", loader);}else{w.onload = loader;}})(window, document);</script>
</li>
      <li>Made in NYC</li>
      <li>&copy; 2013 One Month</li>
    </ul>
    <div class="site-badges">
      <a href="//mixpanel.com/f/partner"><img src="//mixpanel.com/site_media/images/partner/badge_light.png" alt="Mobile Analytics" /></a>

    </div>
  </div>


</footer>
</html>

app/views/pages/about.html.erb
<h1> About us</h1>
<p>Music is one of the best ways to learn English because it is fun and acctively uses your brain. blah blah blah.</p>

app/views/pages/home.html.erb
<div class="jumbotron">
	<h1>Let's Learn English</h1>
	<p>Learn English and improve your accent by learning famous songs!</p>
	<p>Click here to <%= link_to "Sign up", "#", class: "btn btn-primary btn-lg" %> <%= link_to "Log in", "#", class: "btn btn-warning btn-lg" %> </p>
</div>

app/views/pages/lessons.html.erb
<h1>Lessons</h1>
<p>In this section we will have all of the lessons posted for you to work through at your own pace. Each song will be broken down and you will get a vocabulary list and grammar for each one. Also, you will be asked to learn an audio response about what you think the song is about or describing it in some way. </p>

<button type="button" class="btn btn-default" data-container="body" data-toggle="popover" data-placement="left" data-content="Vivamus sagittis lacus vel augue laoreet rutrum faucibus.">
  Popover on left
</button>

<div class="panel-footer">
	<div class="progress">
  	<div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
    <span class="sr-only">60% Complete</span>
  	</div>
	</div>
</div>


<div class="panel-footer">

    <span class="list-group-item-text step-description">Progress:
      25
      /
      46
      54%
    </span>

    <div class="progress progress-striped">
      <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="54" aria-valuemin="0" aria-valuemax="100" style="width: 54%">
        <span class="sr-only">54% Complete (success)</span>
      </div>
    </div>

  </div>